apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  features:
    - name: Resiliency
      enabled: false
    - name: ServiceInvocation.NoDefaultContentType
      enabled: false
