apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
      # Kafka broker connection setting
    - name: brokers
      # Comma separated list of kafka brokers
      value: "localhost:9092"
      # Configure or disable authentication. Supported values: none, password, mtls, or oidc
    - name: authType
      value: "none"
      # The maximum size in bytes allowed for a single Kafka message. Defaults to 1024.
    - name: maxMessageBytes
      value: 1000000
      # The interval between retries when attempting to consume topics. Treats numbers without suffix as milliseconds. Defaults to 100ms.
    - name: consumeRetryInterval
      value: 200ms
      # Disable TLS for transport security. To disable, you’re not required to set value to "true". This is not recommended for use in production. Defaults to "false".
    - name: disableTls
      value: "true"
    - name: skipVerify
      value: "true"